### ISSUE TITLE
User auth from Helm not working. 

### ISSUE THREAD

**Issue by clemenko** [m9sweeper/m9sweeper#305]
From 
```
helm upgrade m9sweeper m9sweeper/m9sweeper -i --create-namespace --namespace m9sweeper-system \
  --set dash.init.superAdminEmail="bob@denver.com" \
  --set dash.init.superAdminPassword="Pa22word" \
  --set-string global.apiKey="YOUR-API-KEY" \
  --set dash.ingress.hosts[0]=m9sweeper.rfed.io \
  --set dash.ingress.k8sIngress.enabled=true
```

I am getting `Invalid auth credential` in the gui. Here is the message from the dash pod. 

```
 UnauthorizedException: Invalid auth credential
    at NonRedirectableLoginController.localAuthLoginAction (/usr/src/app/main.js:2697:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

What am I doing wrong?

**Comment by jacobbeasley** [comment]
You could try helm delete and re-installing. It shouldn't do this, but my guess is that for whatever reason it failed to setup the first user properly.

**Comment by clemenko** [comment]
Clean install I am getting 
`m9sweeper-system   m9sweeper-dash-init-877nw                               0/1     Error       0               52s`

with the following in the logs:
```(node:29) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
(node:29) [DEP0152] DeprecationWarning: Custom PerformanceEntry accessors are deprecated. Please use the detail property.
Error: Invalid argument provided: the specific seed "super-admin-seed.ts" does not exist.
    at FsSeeds.getSeeds (/usr/src/app/node_modules/knex/lib/migrations/seed/sources/fs-seeds.js:47:15)
    at async Seeder.run (/usr/src/app/node_modules/knex/lib/migrations/seed/Seeder.js:22:19)
    at async Promise.all (index 0)
error: select "u"."id" as "_id", "u"."first_name" as "_firstName", "u"."last_name" as "_lastName", "u"."email" as "_email", "u"."phoneadjusted" as "_phone", "u"."is_active" as "_isActive", "u"."password" as "_password", "u"."source_system_id" as "_sourceSystem_id", "u"."source_system_type" as "_sourceSystem_type", "u"."source_system_user_id" as "_sourceSystem_uid", "authority_levels"."id" as "_authorities__id", "authority_levels"."name" as "_authorities__name" from (select *, COALESCE(u.phone, '') AS "phoneadjusted" from "users" as "u" where "email" = $1 order by u.id asc limit $2) as "u" left join "user_authorities" as "user_auth" on "u"."id" = "user_auth"."user_id" and "user_auth"."active" = $3 left join "authority_levels" on "user_auth"."authority_id" = "authority_levels"."id" order by "u"."id" asc - relation "users" does not exist
    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:514:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 105,
  severity: 'ERROR',
  code: '42P01',
  detail: undefined,
  hint: undefined,
  position: '521',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '1180',
  routine: 'parserOpenTable'
}
npm notice 
npm notice New major version of npm available! 9.6.7 -> 10.2.1
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.2.1>
npm notice Run `npm install -g npm@10.2.1` to update!
npm notice 
```


current helm command

```helm upgrade m9sweeper m9sweeper/m9sweeper -i --create-namespace --namespace m9sweeper-system \
  --set dash.init.superAdminEmail="bob@denver.com" \
  --set dash.init.superAdminPassword="Pa22word" \
  --set global.jwtSecret="changeme" \
  --set global.apiKey="YOUR-API-KEYYOUR-API-KEYYOUR-API-KEYYOUR-API-KEY" \
  --set dash.ingress.hosts[0]=m9sweeper.rfed.io \
  --set dash.ingress.k8sIngress.enabled=true

```

**Comment by jacobbeasley** [comment]
Can you guys confirm the command you ran to add m9sweeper to your helm registries? (the one you ran before you installed it)

**Comment by jacobbeasley** [comment]
Trying to confirm which helm repository you're using (we had switched to using github recently)

**Comment by clemenko** [comment]
```
helm repo add m9sweeper https://m9sweeper.github.io/m9sweeper --force-update

helm upgrade m9sweeper m9sweeper/m9sweeper -i --create-namespace --namespace m9sweeper-system \
  --set dash.init.superAdminEmail="bob@denver.com" \
  --set dash.init.superAdminPassword="Pa22word" \
  --set global.jwtSecret="changeme" \
  --set global.apiKey="YOUR-API-KEYYOUR-API-KEYYOUR-API-KEYYOUR-API-KEY" \
  --set dash.ingress.hosts[0]=m9sweeper.rfed.io \
  --set dash.ingress.k8sIngress.enabled=true
```

**Comment by jacobbeasley** [comment]
Okay, so digging into this, there's a race condition because the init job is getting booted up at the same time as the web api and the init job is running (sometimes) before the migrations have run. We had it set to post-install but I guess helm post-install doesn't mean that the apps booted up yet, just that they exist in etcd :D

**Comment by jacobbeasley** [comment]
We'll have a fix out later today or tomorrow. In the meantime, you can theoretically just restart the init job 5 minutes later and it'll work.

**Comment by jacobbeasley** [comment]
Circling back - we released a new version of the app that fixes this race condition last week. Give that a try (you may have to uninstall and reinstall) and let us know if the problem persists.

**Comment by clemenko** [comment]
confirmed working. thanks
